// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvhTI3N723w8n-PIkciYIleS6ggHY0DY',
    appId: '1:447350001382:web:e651e9a9cbfd5af67cb527',
    messagingSenderId: '447350001382',
    projectId: 'campus-thrift-app',
    authDomain: 'campus-thrift-app.firebaseapp.com',
    storageBucket: 'campus-thrift-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx8m_uzbZbBm3hs3T4X8viByCYTWo_hrw',
    appId: '1:447350001382:android:672f37e06e96daa27cb527',
    messagingSenderId: '447350001382',
    projectId: 'campus-thrift-app',
    storageBucket: 'campus-thrift-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0kg-zYuQNkifV9a5JDkXJpQBkzAKuxM',
    appId: '1:447350001382:ios:2487c09116aecf1f7cb527',
    messagingSenderId: '447350001382',
    projectId: 'campus-thrift-app',
    storageBucket: 'campus-thrift-app.firebasestorage.app',
    iosBundleId: 'com.example.campusThrift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa0kg-zYuQNkifV9a5JDkXJpQBkzAKuxM',
    appId: '1:447350001382:ios:2487c09116aecf1f7cb527',
    messagingSenderId: '447350001382',
    projectId: 'campus-thrift-app',
    storageBucket: 'campus-thrift-app.firebasestorage.app',
    iosBundleId: 'com.example.campusThrift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGvhTI3N723w8n-PIkciYIleS6ggHY0DY',
    appId: '1:447350001382:web:c1f278f3077d3f0e7cb527',
    messagingSenderId: '447350001382',
    projectId: 'campus-thrift-app',
    authDomain: 'campus-thrift-app.firebaseapp.com',
    storageBucket: 'campus-thrift-app.firebasestorage.app',
  );
}
